INSERT INTO maps(map_name, map_difficulty)
VALUES
    ('Monkey Meadow', 'Begginer')     ,
    ('In The Loop', 'Begginer')       ,
    ('Middle of the Road', 'Begginer'),
    ('Tree Stump', 'Begginer')        ,
    ('Town Center', 'Begginer')       ,
    ('One Two Tree', 'Begginer')      ,
    ('Scrapyard', 'Begginer')         ,
    ('The Cabin', 'Begginer')         ,
    ('Resort', 'Begginer')            ,
    ('Skates', 'Begginer')            ,
    ('Lotus Island', 'Begginer')      ,
    ('Candy Falls', 'Begginer')       ,
    ('Winter Park', 'Begginer')       ,
    ('Carved', 'Begginer')            ,
    ('Park Path', 'Begginer')         ,
    ('Alpine Run', 'Begginer')        ,
    ('Frozen Over', 'Begginer')       ,
    ('Cubism', 'Begginer')            ,
    ('Four Circles', 'Begginer')      ,
    ('Hedge', 'Begginer')             ,
    ('End of the Road', 'Begginer')   ,
    ('Logs', 'Begginer')              ,

    ('Luminous Cove'   , 'Intermediate'),
    ('Sulfur Springs'  , 'Intermediate'),
    ('Water Park'      , 'Intermediate'),
    ('Polyphemus'      , 'Intermediate'),
    ('Covered Garden'  , 'Intermediate'),
    ('Quarry'          , 'Intermediate'),
    ('Quiet Street'    , 'Intermediate'),
    ('Bloonarius Prime', 'Intermediate'),
    ('Balance'         , 'Intermediate'),
    ('Encrypted'       , 'Intermediate'),
    ('Bazaar'          , 'Intermediate'),
    ('Adora''s Temple' , 'Intermediate'),
    ('Spring Spring'   , 'Intermediate'),
    ('KartsNDarts'     , 'Intermediate'),
    ('Moon Landing'    , 'Intermediate'),
    ('Haunted'         , 'Intermediate'),
    ('Downstream'      , 'Intermediate'),
    ('Firing Range'    , 'Intermediate'),
    ('Cracked'         , 'Intermediate'),
    ('Streambed'       , 'Intermediate'),
    ('Chutes'          , 'Intermediate'),
    ('Rake'            , 'Intermediate'),
    ('Spice Islands'   , 'Intermediate'),
    ('Castle Revenge', 'Advanced'),
    ('Dark Path', 'Advanced'),
    ('Erosion', 'Advanced'),
    ('Midnight Mansion', 'Advanced'),
    ('X Factor', 'Advanced'),
    ('Sunken Columns', 'Advanced'),
    ('Mesa', 'Advanced'),
    ('Geared', 'Advanced'),
    ('Spillway', 'Advanced'),
    ('Cargo', 'Advanced'),
    ('Pat''s Pond', 'Advanced' ),
    ('Peninsula', 'Advanced'),
    ('High Finance', 'Advanced'),
    ('Another Brick', 'Advanced'),
    ('Off The Coast', 'Advanced'),
    ('Cornfield', 'Advanced'),
    ('Underground', 'Advanced'),
    ('Ancient Portal', 'Advanced'),
    ('Glacial Trail', 'Expert'),
    ('Dark Dungeons', 'Expert'),
    ('Sanctuary', 'Expert'),
    ('Ravine', 'Expert'),
    ('Infernal', 'Expert'),
    ('Flooded Valley', 'Expert'),
    ('Bloody Puddles', 'Expert'),
    ('Workshop', 'Expert'),
    ('Quad', 'Expert'),
    ('Dark Castle', 'Expert'),
    ('#Ouch', 'Expert'),
    ('Muddy Puddles', 'Expert'),
    ('Blons', 'Expert');